//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HearDelta.Core.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HearDelta.Core.Localization.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Obergrenze wurde erreicht; die tatsächliche Schwelle kann höher liegen..
        /// </summary>
        public static string Adaptive_MaximumReached {
            get {
                return ResourceManager.GetString("Adaptive_MaximumReached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Noch keine Antwort erfasst..
        /// </summary>
        public static string Adaptive_NoAnswer {
            get {
                return ResourceManager.GetString("Adaptive_NoAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keine falsche Antwort – die Schwelle liegt unterhalb des leisesten erreichten Werts..
        /// </summary>
        public static string Adaptive_NoWrongAnswer {
            get {
                return ResourceManager.GetString("Adaptive_NoWrongAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zu wenige Darbietungen nach der ersten falschen Antwort ({0} von mindestens {1})..
        /// </summary>
        public static string Adaptive_TooFewTrials {
            get {
                return ResourceManager.GetString("Adaptive_TooFewTrials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Kommentar darf höchstens 4.000 Zeichen enthalten..
        /// </summary>
        public static string Annotation_CommentLength {
            get {
                return ResourceManager.GetString("Annotation_CommentLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Name der Messung muss 1 bis {0} Zeichen enthalten..
        /// </summary>
        public static string Annotation_NameLength {
            get {
                return ResourceManager.GetString("Annotation_NameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Regel des adaptiven Verfahrens (Größe, Startwert, Schrittweiten oder Grenzen) ist unterschiedlich..
        /// </summary>
        public static string Compare_AdaptiveRule {
            get {
                return ResourceManager.GetString("Compare_AdaptiveRule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Pegel des Dauerrauschens ist unterschiedlich..
        /// </summary>
        public static string Compare_ContinuousNoiseLevel {
            get {
                return ResourceManager.GetString("Compare_ContinuousNoiseLevel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eine Messung verwendet Dauerrauschen, die andere Rauschen nur während der Stimuli..
        /// </summary>
        public static string Compare_ContinuousVsStimulusNoise {
            get {
                return ResourceManager.GetString("Compare_ContinuousVsStimulusNoise", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Das geprüfte Ohr ist unterschiedlich..
        /// </summary>
        public static string Compare_Ear {
            get {
                return ResourceManager.GetString("Compare_Ear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Hörumgebung ist unterschiedlich..
        /// </summary>
        public static string Compare_Environment {
            get {
                return ResourceManager.GetString("Compare_Environment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eine Messung verwendet einen festen, die andere einen adaptiven Pegel..
        /// </summary>
        public static string Compare_FixedVsAdaptive {
            get {
                return ResourceManager.GetString("Compare_FixedVsAdaptive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Das Sprachmaterial ist unterschiedlich..
        /// </summary>
        public static string Compare_Material {
            get {
                return ResourceManager.GetString("Compare_Material", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die vollständige Materialidentität fehlt in mindestens einer Sitzung..
        /// </summary>
        public static string Compare_MaterialIdentityMissing {
            get {
                return ResourceManager.GetString("Compare_MaterialIdentityMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nur abgeschlossene Sitzungen können gegenübergestellt werden..
        /// </summary>
        public static string Compare_OnlyCompleted {
            get {
                return ResourceManager.GetString("Compare_OnlyCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der unveränderliche Fingerabdruck des Stimuluspakets ist unterschiedlich..
        /// </summary>
        public static string Compare_PackFingerprint {
            get {
                return ResourceManager.GetString("Compare_PackFingerprint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stimuluspaket oder Katalogversion sind unterschiedlich..
        /// </summary>
        public static string Compare_PackOrCatalog {
            get {
                return ResourceManager.GetString("Compare_PackOrCatalog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mindestens ein Katalog- oder Wiedergabenachweis fehlt..
        /// </summary>
        public static string Compare_RecordMissing {
            get {
                return ResourceManager.GetString("Compare_RecordMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Renderverfahren, Normalisierung oder tatsächlicher Digitalpegel sind unterschiedlich..
        /// </summary>
        public static string Compare_Render {
            get {
                return ResourceManager.GetString("Compare_Render", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Signal-Rausch-Abstand ist unterschiedlich oder nicht eindeutig dokumentiert..
        /// </summary>
        public static string Compare_Snr {
            get {
                return ResourceManager.GetString("Compare_Snr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Prüfsumme der Kopfhörerentzerrung stimmt nicht..
        /// </summary>
        public static string Equalization_Checksum {
            get {
                return ResourceManager.GetString("Equalization_Checksum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zeile {0}: Die Preamp-Angabe ist doppelt..
        /// </summary>
        public static string Equalization_DuplicatePreamp {
            get {
                return ResourceManager.GetString("Equalization_DuplicatePreamp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Kopfhörerentzerrung muss 1 bis {0} aktive Filter enthalten..
        /// </summary>
        public static string Equalization_FilterCount {
            get {
                return ResourceManager.GetString("Equalization_FilterCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Filterfrequenz {0} Hz ist bei dieser Abtastrate nicht darstellbar..
        /// </summary>
        public static string Equalization_FilterFrequency {
            get {
                return ResourceManager.GetString("Equalization_FilterFrequency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eine Filterverstärkung liegt außerhalb von ±30 dB..
        /// </summary>
        public static string Equalization_FilterGain {
            get {
                return ResourceManager.GetString("Equalization_FilterGain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eine Filtergüte liegt außerhalb von 0,05 bis 20..
        /// </summary>
        public static string Equalization_FilterQ {
            get {
                return ResourceManager.GetString("Equalization_FilterQ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ein Filtertyp ist ungültig..
        /// </summary>
        public static string Equalization_FilterType {
            get {
                return ResourceManager.GetString("Equalization_FilterType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zeile {0}: „{1}“ ist keine gültige AutoEq-Filterzeile..
        /// </summary>
        public static string Equalization_InvalidLine {
            get {
                return ResourceManager.GetString("Equalization_InvalidLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Preamp-Angabe fehlt..
        /// </summary>
        public static string Equalization_PreampMissing {
            get {
                return ResourceManager.GetString("Equalization_PreampMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Preamp-Angabe liegt außerhalb von ±30 dB..
        /// </summary>
        public static string Equalization_PreampRange {
            get {
                return ResourceManager.GetString("Equalization_PreampRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} · {1}.
        /// </summary>
        public static string Level_Combined {
            get {
                return ResourceManager.GetString("Level_Combined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to vom {0:dd.MM.}.
        /// </summary>
        public static string Level_DateSuffix {
            get {
                return ResourceManager.GetString("Level_DateSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to geschätzte Ruheschwelle {0:0.#} dB (Tonmittel {1:0.#} dBFS{2} {3} dB).
        /// </summary>
        public static string Level_EstimatedQuietThreshold {
            get {
                return ResourceManager.GetString("Level_EstimatedQuietThreshold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SNR: kein Störgeräusch-Vortest – bisheriger Wert.
        /// </summary>
        public static string Level_NoNoisePretest {
            get {
                return ResourceManager.GetString("Level_NoNoisePretest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start-SNR: kein Störgeräusch-Vortest – 0 dB.
        /// </summary>
        public static string Level_NoNoisePretestStart {
            get {
                return ResourceManager.GetString("Level_NoNoisePretestStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kein passender Vortest – Startpegel des Messprofils..
        /// </summary>
        public static string Level_NoPretest {
            get {
                return ResourceManager.GetString("Level_NoPretest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lautstärke: kein Ruhe-Vortest – Startpegel des Messprofils.
        /// </summary>
        public static string Level_NoQuietPretest {
            get {
                return ResourceManager.GetString("Level_NoQuietPretest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ruheschwelle {0:0.#} dB{1}.
        /// </summary>
        public static string Level_QuietThreshold {
            get {
                return ResourceManager.GetString("Level_QuietThreshold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SNR: Störgeräuschschwelle {0} dB{1} {2} dB.
        /// </summary>
        public static string Level_SnrSource {
            get {
                return ResourceManager.GetString("Level_SnrSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} {1} dB.
        /// </summary>
        public static string Level_SourceOffset {
            get {
                return ResourceManager.GetString("Level_SourceOffset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lautstärke: {0} {1} dB.
        /// </summary>
        public static string Level_SpeechSource {
            get {
                return ResourceManager.GetString("Level_SpeechSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Bittiefe des gespeicherten Audioausgangs hat sich geändert..
        /// </summary>
        public static string Profile_BitDepthChanged {
            get {
                return ResourceManager.GetString("Profile_BitDepthChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Bittiefe ist ungültig..
        /// </summary>
        public static string Profile_BitDepthInvalid {
            get {
                return ResourceManager.GetString("Profile_BitDepthInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Kanalzahl des gespeicherten Audioausgangs hat sich geändert..
        /// </summary>
        public static string Profile_ChannelsChanged {
            get {
                return ResourceManager.GetString("Profile_ChannelsChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Verstärkerausgang ist unterschiedlich..
        /// </summary>
        public static string Profile_DiffAmplifier {
            get {
                return ResourceManager.GetString("Profile_DiffAmplifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der dokumentierte Kalibrierstatus ist unterschiedlich..
        /// </summary>
        public static string Profile_DiffCalibration {
            get {
                return ResourceManager.GetString("Profile_DiffCalibration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der gespeicherte WASAPI-Ausgang ist unterschiedlich..
        /// </summary>
        public static string Profile_DiffEndpoint {
            get {
                return ResourceManager.GetString("Profile_DiffEndpoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Kopfhörerentzerrung ist unterschiedlich..
        /// </summary>
        public static string Profile_DiffEqualization {
            get {
                return ResourceManager.GetString("Profile_DiffEqualization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Das gespeicherte Audioformat ist unterschiedlich..
        /// </summary>
        public static string Profile_DiffFormat {
            get {
                return ResourceManager.GetString("Profile_DiffFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Gain-Einstellung ist unterschiedlich..
        /// </summary>
        public static string Profile_DiffGain {
            get {
                return ResourceManager.GetString("Profile_DiffGain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Kopfhörer-Snapshot ist unterschiedlich..
        /// </summary>
        public static string Profile_DiffHeadphone {
            get {
                return ResourceManager.GetString("Profile_DiffHeadphone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Digitaler Messpegel oder Pegelobergrenze sind unterschiedlich..
        /// </summary>
        public static string Profile_DiffLevel {
            get {
                return ResourceManager.GetString("Profile_DiffLevel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der WASAPI-Ausgabemodus ist unterschiedlich..
        /// </summary>
        public static string Profile_DiffMode {
            get {
                return ResourceManager.GetString("Profile_DiffMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der gespeicherte Audioausgang ist nicht verfügbar. Es wurde kein Ersatzgerät gewählt..
        /// </summary>
        public static string Profile_EndpointUnavailable {
            get {
                return ResourceManager.GetString("Profile_EndpointUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Kopfhörerhersteller fehlt..
        /// </summary>
        public static string Profile_HeadphoneManufacturerMissing {
            get {
                return ResourceManager.GetString("Profile_HeadphoneManufacturerMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Das Kopfhörermodell fehlt..
        /// </summary>
        public static string Profile_HeadphoneModelMissing {
            get {
                return ResourceManager.GetString("Profile_HeadphoneModelMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die digitale Pegelobergrenze darf 0 dB nicht überschreiten..
        /// </summary>
        public static string Profile_MaximumAboveZero {
            get {
                return ResourceManager.GetString("Profile_MaximumAboveZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Das Messprofil benötigt einen Namen..
        /// </summary>
        public static string Profile_NameRequired {
            get {
                return ResourceManager.GetString("Profile_NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ein erkannter Audioausgang muss ausgewählt werden..
        /// </summary>
        public static string Profile_OutputRequired {
            get {
                return ResourceManager.GetString("Profile_OutputRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Abtastrate des gespeicherten Audioausgangs hat sich geändert..
        /// </summary>
        public static string Profile_SampleRateChanged {
            get {
                return ResourceManager.GetString("Profile_SampleRateChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Abtastrate ist ungültig..
        /// </summary>
        public static string Profile_SampleRateInvalid {
            get {
                return ResourceManager.GetString("Profile_SampleRateInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Startlautstärke darf die Obergrenze nicht überschreiten..
        /// </summary>
        public static string Profile_StartAboveMaximum {
            get {
                return ResourceManager.GetString("Profile_StartAboveMaximum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Audioausgang muss mindestens zwei Kanäle bereitstellen..
        /// </summary>
        public static string Profile_TwoChannels {
            get {
                return ResourceManager.GetString("Profile_TwoChannels", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eine Messserie benötigt mindestens zwei getrennte Stimuluslisten..
        /// </summary>
        public static string Series_TwoLists {
            get {
                return ResourceManager.GetString("Series_TwoLists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mindestens ein älterer Test wurde mit Hörgerät gemessen; Hörgeräte unterdrücken Sinustöne..
        /// </summary>
        public static string ThresholdCompare_LegacyAid {
            get {
                return ResourceManager.GetString("ThresholdCompare_LegacyAid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Vertäubung des Gegenohrs ist unterschiedlich..
        /// </summary>
        public static string ThresholdCompare_Masking {
            get {
                return ResourceManager.GetString("ThresholdCompare_Masking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Pegelobergrenze ist unterschiedlich..
        /// </summary>
        public static string ThresholdCompare_Maximum {
            get {
                return ResourceManager.GetString("ThresholdCompare_Maximum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Protokollversion und damit das Messverfahren sind unterschiedlich..
        /// </summary>
        public static string ThresholdCompare_Protocol {
            get {
                return ResourceManager.GetString("ThresholdCompare_Protocol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tonsignal oder Pegelschritt sind unterschiedlich (Protokollversion)..
        /// </summary>
        public static string ThresholdCompare_Signal {
            get {
                return ResourceManager.GetString("ThresholdCompare_Signal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Startpegel ist unterschiedlich..
        /// </summary>
        public static string ThresholdCompare_Start {
            get {
                return ResourceManager.GetString("ThresholdCompare_Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Tonkatalog ist unterschiedlich..
        /// </summary>
        public static string ThresholdCompare_ToneCatalog {
            get {
                return ResourceManager.GetString("ThresholdCompare_ToneCatalog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Pegelobergrenze des Messprofils darf 0 dBFS nicht überschreiten..
        /// </summary>
        public static string Threshold_MaximumAboveZero {
            get {
                return ResourceManager.GetString("Threshold_MaximumAboveZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Der Startpegel darf höchstens {0:0.##} dBFS betragen ({1:0} dB unter der Pegelobergrenze)..
        /// </summary>
        public static string Threshold_StartTooHigh {
            get {
                return ResourceManager.GetString("Threshold_StartTooHigh", resourceCulture);
            }
        }
    }
}
